name: Deploy to BunnyCDN

on:
    push:
        branches: ["main"]
        paths-ignore: ["**.md"]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Add tracking script
              uses: jacobtomlinson/gha-find-replace@v3
              with:
                find: "</head>"
                replace: <script async src="https://analytics.jackbailey.dev/script.js" data-website-id="b7f60d8a-26ef-41c1-8311-becfc0b038f5"></script></head>
                regex: false
                include: "src/index.html"
            - name: Deploy to BunnyCDN
              uses: ayeressian/bunnycdn-storage-deploy@v2.0.0
              with:
                  source: "src"
                  storageZoneName: "${{ secrets.STORAGE_NAME }}"
                  storagePassword: "${{ secrets.STORAGE_PASSWORD }}"
                  accessKey: "${{ secrets.STORAGE_KEY }}"
                  pullZoneId: "${{ secrets.ZONE_ID }}"
                  remove: "true"
                  purge: "true"
            