name: "Update Release"
on:
    workflow_dispatch:
      inputs:
        lynx_version:
          type: string
          description: Lynx Version
    schedule:
        - cron: "0 * * * *"
    
jobs:
    update-release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v3
            - name: switching from HTTPS to SSH
              run: git remote set-url origin git@github.com:Lynx-Shortener/Website.git
            - name: Get Local Version
              run: |
                LYNX_VERSION="${{ github.event.inputs.lynx_version }}"
                echo "LYNX_VERSION=$LYNX_VERSION" >> $GITHUB_ENV

                LOCAL_VERSION=$(grep -o '<span id="version">.*</span>' src/index.html | cut -d '>' -f 2 | cut -d '<' -f1)
                echo "LOCAL_VERSION=$LOCAL_VERSION" >> $GITHUB_ENV
            - name: Replace Version in Header
              if: env.LYNX_VERSION != env.LOCAL_VERSION
              run: |
                sed -i -r 's|<span id="version">[0-9]+(\.[0-9]\.[0-9]+)*</span>|<span id="version">${{ env.LYNX_VERSION }}</span>|g' src/index.html
            - uses: webfactory/ssh-agent@v0.7.0
              if: env.LYNX_VERSION != env.LOCAL_VERSION
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            - name: Import GPG key
              uses: crazy-max/ghaction-import-gpg@v5
              if: env.LYNX_VERSION != env.LOCAL_VERSION
              with:
                  gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
                  passphrase: ${{ secrets.GPG_PASSPHRASE }}
                  git_user_signingkey: true
                  git_commit_gpgsign: true
            - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
              if: env.LYNX_VERSION != env.LOCAL_VERSION
              with:
                  add: 'src/index.html'
                  author_name: Jack Bailey
                  author_email: jack@getlynx.dev
                  message: '[AUTO] Update version from ${{ env.LOCAL_VERSION }} to ${{ env.LYNX_VERSION }}'
                  commit: -S
